print("Gemmimah Sabida Hernandez")
print("Purok-5 Mahunig, Gasan, Marinduque")
print("September 15, 2001")
print("Marinduque State College")
print("Bachelor of Science in Information Technology")
print("Second year college")
print("Section E")
print("1.Walking at the seashore.")
print("2.Listening music.")
print("3.Watching videos of k-pop girl group TWICE in youtube.")
print("4.Eating and chilling.")
print("5.Taking picture of beautiful scenery like seascape photographs.")