print("Gemmimah Sabida Hernandez")
print("Purok-5 Mahunig, Gasan, Marinduque")
print("September 15, 2001")
print("Marinduque State College")
print("Bachelor of Science in Information Technology")
print("Second year college")
print("Section E")